export enum ETypographyVariants {
  'Heading1' = 'Heading1',
  'Heading2' = 'Heading2',
  'Heading3' = 'Heading3',
  'Heading4' = 'Heading4',
  'Subheading1' = 'Subheading1',
  'Subheading2' = 'Subheading2',
  'Subheading3' = 'Subheading3',
  'Body' = 'Body',
  'Body-Medium' = 'Body-Medium',
  'Body-Bold' = 'Body-Bold',
  'Body1' = 'Body1',
  'Body1-Medium' = 'Body1-Medium',
  'Body1-Bold' = 'Body1-Bold',
  'Body2' = 'Body2',
  'Body2-Medium' = 'Body2-Medium',
  'Body2-Bold' = 'Body2-Bold',
  'Caption' = 'Caption',
  'Caption-Medium' = 'Caption-Medium',
  'Caption-Bold' = 'Caption-Bold',
  'Caption1'='Caption1',
  'Caption1-Medium'='Caption1-Medium',
  'Caption1-Bold'='Caption1-Bold'
}